<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1522480575660" stop="1522480575701">
  <name>test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1522480575660" status="passed" stop="1522480575670">
      <name>TestLogin.test_login1</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="6740-MainThread"/>
        <label name="host" value="DESKTOP-JGOP051"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1522480575671" status="failed" stop="1522480575701">
      <name>TestLogin.test_login2</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x000001BB8CA4F588&gt;

    def test_login2(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:7: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="6740-MainThread"/>
        <label name="host" value="DESKTOP-JGOP051"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
